MODEL:
  MODEL_NAME: "Two_stream_fusion"
  TYPE:  "two_stream"
  FUSION_METHOD: "Late"
  BILINEAR_OUT_DIM: 512
  ATTENTION:  True
  NUM_CLSTM_LAYERS: 4
  LSTM_HIDDEN_SIZE: 32
  CLSTM_HIDDEN_SIZE: 32
  NUM_LSTM_LAYERS:  4
  IMG_SIZE: (112, 112)
  NUM_LABELS: 2
DATA:
  REQUIRE_AUX: False
  DATA_TYPE: "simple"
  BALANCE_POLICY: 2 
  CLIP_LENGTH: 8
SOLVER:
  METHOD: "sgd"
  LR_POLICY:  "steps_with_relative_lrs" 
  BASE_LR: 0.01
  MOMENTUM: 0.9
  WEIGHT_DECAY:  1e-4
  DAMPENING:  0.0
  NESTEROV: True
  LRS: [1, 0.1, 0.01, 0.001]
  STEPS:  [0,27,41,51]
  MAX_EPOCH:  60
RUN:
  TEST_BATCH_SIZE:  1
  TRAIN_BATCH_SIZE: 16